name: poke_teste
description: Teste do caio para a Conta Azul

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

flutter_native_splash:
  color: "#1E1E1E"
  image: "assets/png/logo.png"
  android: true
  ios: true

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  flutter_secure_storage: ^8.0.0
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.3.1
  http: ^0.13.3
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.7
  flutter_animate: ^4.1.1+1
  cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.2
  flutter_modular: 5.0.3
  flutter_value_notifier: ^1.5.1
  dio: ^5.5.0+1
  skeleton_loader: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/icons/

dependency_overrides:
  intl: ^0.18.0
  http: ^1.0.0
